### ISSUE TITLE
Add a Toast for lettting people know there is a help request

### ISSUE THREAD

**Issue by joemellin** [vsls-contrib/communities#60] opened 2019-08-19 18:20 UTC
When a help request is created, create a toast for the other online users in the same community.

![bda07326-d264-46e8-93b0-69ae6cf16076](https://user-images.githubusercontent.com/1232282/63289144-3eac0800-c273-11e9-8309-1e73b1990255.jpg)

**Comment by lostintangent** [comment] 2019-08-21 15:34
Duplicate of #38.

**Closed by lostintangent** 2019-08-21 15:34 UTC
